apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-website
  labels:
    app: argocd-website
spec:
  replicas: 5
  selector:
    matchLabels:
      app: argocd-website
  template:
    metadata:
      labels:
        app: argocd-website
    spec:
      containers:
        - name: nginx
          image: ghcr.io/moiz-ali-moomin/argocd-website:efa713e65b14638358029951e2e08818b1cdf009
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
