apiVersion: v1
kind: Service
metadata:
  name: argocd-website-svc
spec:
  type: NodePort
  selector:
    app: argocd-website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
