apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: replica-patch.yaml
- path: resource-patch.yaml
- path: ingress-patch.yaml
images:
- name: ghcr.io/moiz-ali-moomin/argocd-website
  newName: ghcr.io/moiz-ali-moomin/argocd-website
  newTag: 6d77ab3b163bb9ff58e66929efc954824406179d
