apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: replica-patch.yaml
- path: resource-patch.yaml
- path: ingress-patch.yaml
images:
- name: ghcr.io/moiz-ali-moomin/argocd-website
  newName: ghcr.io/moiz-ali-moomin/argocd-website
  newTag: f5e972608c065df5a3a82429b998a8a533ea1fd6
